bind 0.0.0.0
protected-mode no

port 6379
timeout 0
tcp-keepalive 300

# 密码（必须改）
requirepass 2000826Li@

# 持久化
appendonly yes
appendfilename "appendonly.aof"

save 900 1
save 300 10
save 60 10000

dir /data

# 日志
loglevel notice
logfile ""

